services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: lunchtech-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/lunchtech?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: lunchtech_user
      SPRING_DATASOURCE_PASSWORD: password_user
    depends_on:
      mysql_db:
        condition: service_healthy
  mysql_db:
    image: mysql:oracle
    container_name: mysql_db_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: lunchtech_root
      MYSQL_DATABASE: lunchtech
      MYSQL_USER: lunchtech_user
      MYSQL_PASSWORD: password_user
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u$$MYSQL_USER", "-p$$MYSQL_PASSWORD" ]
      interval: 5s
      timeout: 3s
      retries: 20
volumes:
  mysql_data: