services:
  mysql_service:
    image: mysql:oracle
    container_name: mysql_db_service
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: lunchtech_root
      MYSQL_DATABASE: lunchtech
      MYSQL_USER: lunchtech_user
      MYSQL_PASSWORD: password_user
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: